# Change these first
owner: kobra-dev # Your GitHub organization or username, where this repository lives
repo: status-upptime # The name of this repository

sites:
  - name: website
    url: https://kobra.dev/
  - name: studio
    url: https://studio.kobra.dev/
  - name: Docs
    url: https://docs.kobra.dev/

status-website:
   baseUrl: /status-upptime

